version: '2'

services:
  web:
    container_name: "Jun_Nginx"
    image: 'nginx:1.13.0'
    ports:
      - 80:80
      - 443:443
    links:
      - mysql
      - redis
      - php
    volumes:
      - ./app:/data/www
      - ./nginx/vhost:/etc/nginx/conf.d
      - ./nginx/logs:/data/logs
    networks:
      - backend
    command: nginx -g "daemon off;"
    tty: true

  php:
    container_name: "Jun_PHP"
    image: 'php:7.2-fpm-alpine'
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www/html
    networks:
      - backend

  redis:
    container_name: "Jun_Redis"
    image: 'redis'
    ports:
      - 6379:6379
    networks:
      - backend

  mysql:
    container_name: "Jun_MySQL"
    image: 'mysql:5.7'
    ports:
      - 3306:3306
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/data:/var/lib/mysql

networks:
  backend:
    driver: bridge
volumes:
  mysql:
    driver: local
