version: '2'

services:

### Web ################################################
  web:
    container_name: "Jun_Nginx"
    image: 'nginx:${NGINX_VERSION}'
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    links:
      - mysql
      - redis
      - memcached
      - php
    depends_on:
      - "${PMA_DB_ENGINE}"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_VHOST_PATH}:/etc/nginx/conf.d
      - ${NGINX_LOGS_PATH}:/data/logs
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - backend
    command: nginx -g "daemon off;"
    tty: true
    restart: always

### Php ################################################
  php:
    container_name: "Jun_PHP"
    build:
      context: ./php
    # image: "php:${PHP_VERSION}"
    volumes:
      - ${APP_CODE_PATH_HOST}:${PHP_CODE_PATH_CONTAINER}
    expose:
      - "9000"
    links:
      - mysql
      - redis
    depends_on:
      - "${PMA_DB_ENGINE}"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - backend
    restart: always

### Redis ################################################
  redis:
    container_name: "Jun_Redis"
    image: 'redis'
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - backend
    restart: always

### MySQL ################################################
  mysql:
    container_name: "Jun_MySQL"
    image: 'mysql:${MYSQL_VERSION}'
    ports:
      - "${MYSQL_PORT}:3306"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    restart: always


### phpMyAdmin ###########################################
  phpmyadmin:
    container_name: "Jun_PHPMyMySQL"
    # build: ./phpmyadmin
    image: "phpmyadmin/phpmyadmin"
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - "${PMA_DB_ENGINE}"
    networks:
      - backend
    restart: always

### Memcached ############################################
  memcached:
    container_name: "Jun_Memcached"
    image: memcached:${MEMCACHED_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/memcached:/var/lib/memcached
    ports:
      - "${MEMCACHED_HOST_PORT}:11211"
    command: memcached
    depends_on:
      - "${PMA_DB_ENGINE}"
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
volumes:
  web:
    driver: ${VOLUMES_DRIVER}
  php:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
  mysql:
    driver: ${VOLUMES_DRIVER}
  phpmyadmin:
    driver: ${VOLUMES_DRIVER}
  memcached:
    driver: ${VOLUMES_DRIVER}
